dataset: "cho_img"

use_compile: False
enable_xformers_memory_efficient_attention: True
gradient_checkpointing: True
use_magic: False 
SophiaG: False
lr: 1e-4
weight_decay: 0

use_margin: True
margin: 0.01

use_clip_norm: True
clip_max_norm: 1.0
start_clip_epoch: 25

adjacency_weight: True

use_covariance: True  # to compute cov
balance_alpha: 0.1
use_local_attention: True  # to use cross attention after mamba 


global_seed: 25126
accumulation_steps: 1   #or 10
log_every: 10
ckpt_every_encoder: 20_000

image_size: 128
ckpt_every: 20_000
num_workers: 16
dt_rank: 16 
d_state: 128
use_image_num: 8  
frame_interval: 3
num_frames: 17
frame_num_in_video: 25

use_wt: True
wt_margin: 0.01

results_dir: "results/cho"
frame_data_txt: "/root/code/MedSora/datasets/CholecTriplet_list.txt"
frame_data_path: "/root/code/MedSora/"
data_path: "/root/code/MedSora/datasets/CholecTriplet"

#load from pre-train
init_from_pretrain_ckpt: False
pretrain_ckpt_path: "results/cho/019-MedSora-B-2/checkpoints/1570000.pt"
init_train_steps: 1570_000


#sample
load_ckpt_type: "ema"  #model, ema
num_sampling_steps: 250
test_data_path: "datasets/CholecTriplet"
sample_global_seed: 25127
sample_num_workers: 4
create_video_num: 2048  #for noise2video
sample_method: "ddim"  #ddim, ddpm
save_video_path: "./sample_results/cho_sample"


pretrain_alpha: 1.0
frame_K: 4
pretrain_lambda_param: 1


# VAE
vae_results_dir: "results/vae/cho"
vae_global_seed: 25126
vae_epochs: 300
vae_batch_size: 1
vae_test_results_dir: "results/vae/cho/test/"
vae_lr: 2.0e-7
vae_ffl_weight: 0.1
vae_lpips_weight: 0.1
#load from pre-train-vae
vae_init_from_pretrain_ckpt: False
vae_pretrain_ckpt_path:  "" 

vae_sample_batch_size: 1
vae_test_ckpt: ""

# flow model
flow_model_path: "/root/code/MedSora/flow_models/raft-things.pth"

# DINO model
# dino_model_type: "dinov2_vitb14"  #dinov2_vits14, dinov2_vitb14, dinov2_vitl14, dinov2_vitg14
dino_weights_path: "/root/code/MedSora/dino_model/dino_vitbase8_pretrain_full_checkpoint.pth"  #dino_vits16, dino_vits8, dino_vitb16, dino_vitb8, dino_resnet50

vae_weight_path: ""